CREATE SEQUENCE HIBERNATE_SEQUENCE START 1 INCREMENT 1;
CREATE TABLE PRODUCT_AUD (ID INT4 NOT NULL, REV INT4 NOT NULL, REVTYPE INT2, DESCRIPTION VARCHAR(255), NAME VARCHAR(100), PRICE NUMERIC(19, 2), PRIMARY KEY (ID, REV));
CREATE TABLE REVINFO (REV INT4 NOT NULL, REVTSTMP INT8, PRIMARY KEY (REV));